### PR TITLE
Day 1 task 2 completed

### PR DESCRIPTION
**Pull request by sndrkrshnn**
modularised the code for better structure. Task 2 completed for day 1

### CODE REVIEW

**Review by sndrkrshnn — COMMENTED** [review]
Couldnt find any conflicts so to speak.. just the DS_store thing.. should be fine to merge

**Comment by jherrlin** [comment]
Nice!

**Comment by jherrlin** [comment]
@sundarakrishnang you need to resolve the conflict before it can be merged

**Comment by jherrlin** [comment]
have you done a `git pull --rebase upstream/main`?

**Pull request closed without merging**
